@extends('layouts.landing')

@section('title', 'Document Verified - ' . ($settings['system_name'] ?? 'System'))

@section('content')
<div class="min-h-screen bg-gradient-to-br from-gray-50 to-gray-100 py-12 px-4 sm:px-6 lg:px-8 flex items-center justify-center">
    <div class="max-w-lg w-full">
        <div class="bg-white rounded-2xl shadow-xl p-8 border border-gray-200">
            <div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                </svg>
            </div>

            <h1 class="text-2xl font-bold text-gray-900 mb-2 text-center">Document Verified</h1>
            <p class="text-gray-600 mb-6 text-center">This export was issued by {{ $settings['system_name'] ?? 'the system' }} and is authentic.</p>

            <dl class="space-y-3 text-sm">
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Document</dt>
                    <dd class="font-medium text-gray-900 text-right">{{ $verification->documentTypeLabel() }}</dd>
                </div>
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Reference</dt>
                    <dd class="font-mono font-semibold text-indigo-600 text-right">{{ $verification->reference_code }}</dd>
                </div>
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Generated</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->created_at?->format('M d, Y h:i A') }}</dd>
                </div>
                @if($verification->generator)
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Generated By</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->generator->name }}</dd>
                </div>
                @endif
                @if(!empty($verification->metadata['record_count']))
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Records</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->metadata['record_count'] }}</dd>
                </div>
                @endif
                @if(!empty($verification->metadata['filters']['type']))
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Type Filter</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->metadata['filters']['type'] }}</dd>
                </div>
                @endif
                @if(!empty($verification->metadata['filters']['department']))
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Department</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->metadata['filters']['department'] }}</dd>
                </div>
                @endif
                @if(!empty($verification->metadata['filters']['employee']))
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Employee</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->metadata['filters']['employee'] }}</dd>
                </div>
                @endif
                @if(!empty($verification->metadata['filters']['date_range']))
                <div class="flex justify-between gap-4 border-b border-gray-100 pb-2">
                    <dt class="text-gray-500">Date Range</dt>
                    <dd class="text-gray-900 text-right">{{ $verification->metadata['filters']['date_range'] }}</dd>
                </div>
                @endif
            </dl>

            <p class="text-xs text-gray-500 mt-6 text-center">If the details above do not match your copy of the document, it may have been altered.</p>

            <div class="mt-6 text-center">
                <a href="{{ url('/') }}" class="inline-flex items-center px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors">
                    Go to Home
                </a>
            </div>
        </div>
    </div>
</div>
@endsection
