; memory_limit = 512M
; max_execution_time = 3600
; max_input_time = 3600
; post_max_size = 5120M
; upload_max_filesize = 5120M
; max_file_uploads = 20

memory_limit = 512M
max_execution_time = 0
post_max_size = 5120M
upload_max_filesize = 5120M
max_file_uploads = 50
